import type { Client } from '../types'

// Real client data — PROJEKTA S.A
// statusReceptivo and statusDataCrazy derived from sub-object statuses
export const seedClients: Client[] = [
  {
    id: 'client-1779288516850-9ndrp',
    nome: 'PROJEKTA S.A',
    nomeConhecido: 'PROJEKTA',
    responsavel: 'João Santiago',
    whatsapp: '47 9685-6030',
    email: '',
    ddd: '47',
    cnpj: '32.965.946/0001-89',
    razaoSocial: 'PROJEKTA S.A LTDA',
    nomeFantasia: 'SANTIAGO RACING BRASIL',
    observacoesCNPJ: '',
    observacoesGerais: '',
    statusGeral: 'Aguardando 24h',
    statusReceptivo: 'Em configuração',   // derived from numeroReceptivo.statusFinal = 'Conectando no DataCrazy'
    statusAtivo: 'Não iniciado',
    statusDataCrazy: 'Pronto',            // derived from dataCrazy.status = 'Pronto'
    proximaAcao: 'Aguardar 24h e acessar novamente para iniciar criação/verificação da BM',
    prazoProximaAcao: '2026-05-21T14:53:49.176Z',
    prioridade: 'Alta',
    pendencia: '',
    facebook: {
      linkPerfil: 'Projekta',
      loginInformado: '',
      statusAcesso: 'Senha armazenada em local seguro',
      codigoSolicitado: true,
      codigoRecebido: true,
      primeiroAcessoRealizado: true,
      dataPrimeiroAcesso: '2026-05-20T14:53:49.176Z',
      segundoAcessoRealizado: true,
      dataSegundoAcesso: '2026-05-20T14:53:49.176Z',
      observacoes: '',
    },
    bmReceptiva: {
      nome: 'BM Projekta Principal - Receptivo',
      idBM: '',
      status: 'Aprovada',
      cnpjUsado: '',
      dominio: 'projektasa.com',
      siteFTMCriado: false,
      linkSiteFTM: 'projektasa.com',
      dataCriacao: '2026-05-17T14:50:00.000Z',
      dataEnvioVerificacao: '2026-05-17T14:50:00.000Z',
      dataAprovacao: '',
      motivoRecusa: '',
      observacoes: '',
      checklist: {
        bmCriada: true,
        dadosCNPJPreenchidos: true,
        siteFTMCriado: true,
        dominiComprado: true,
        dominioVinculado: true,
        verificacaoEnviada: true,
        bmEmAnalise: true,
        bmAprovada: true,
        bmRecusada: true,
      },
    },
    numeroReceptivo: {
      ddd: '47',
      numero: '47 9245-8321',
      operadora: 'Vivo',
      statusChip: 'Ativo',
      dataAtivacao: '2026-05-18T14:51:00.000Z',
      conectadoBM: true,
      conectadoDataCrazy: true,
      podeDisparar: false,
      testeRealizado: true,
      statusFinal: 'Conectando no DataCrazy',
      observacoes: '',
      checklist: {
        numeroSeparado: true,
        chipAtivado: true,
        conectadoBM: true,
        conectadoDataCrazy: true,
        testeRealizado: true,
        pronto: true,
      },
    },
    bmAtiva: {
      nome: '',
      idBM: '',
      status: 'Não iniciada',
      cnpjUsado: '',
      dominio: '',
      siteFTMCriado: false,
      linkSiteFTM: '',
      dataCriacao: '',
      dataEnvioVerificacao: '',
      dataAprovacao: '',
      motivoRecusa: '',
      observacoes: '',
      checklist: {
        bmCriada: false,
        dadosCNPJPreenchidos: false,
        siteFTMCriado: false,
        dominiComprado: false,
        dominioVinculado: false,
        verificacaoEnviada: false,
        bmEmAnalise: false,
        bmAprovada: false,
        bmRecusada: false,
      },
    },
    numeroAtivo: {
      ddd: '47',
      numero: '',
      operadora: 'Vivo',
      statusChip: '',
      dataAtivacao: '',
      conectadoBM: false,
      conectadoDataCrazy: false,
      podeDisparar: false,
      testeRealizado: false,
      statusFinal: 'Não iniciado',
      observacoes: '',
      checklist: {
        numeroSeparado: false,
        chipAtivado: false,
        conectadoBM: false,
        conectadoDataCrazy: false,
        testeRealizado: false,
        pronto: false,
      },
    },
    dataCrazy: {
      clienteCriado: true,
      ambiente: 'KSJ Comércio Digital',
      numeroReceptivoVinculado: '47 9245-8321',
      numeroAtivoVinculado: '',
      funilConfigurado: true,
      tagsCriadas: false,
      automacoesReceptivasCriadas: true,
      automacoesAtivasCriadas: false,
      disparoConfigurado: false,
      ultimoTeste: '2026-05-19T14:52:00.000Z',
      status: 'Pronto',
      observacoes: '',
      automacoes: [],
    },
    historico: [
      {
        id: 'h-1779288516850-hq7ar',
        dataHora: '2026-05-20T14:48:36.850Z',
        tipo: 'cadastro',
        descricao: 'Cliente cadastrado no sistema',
        responsavel: 'Rafael',
        observacao: '',
      },
      {
        id: 'h-1779288653923-x2thp',
        dataHora: '2026-05-20T14:50:53.923Z',
        tipo: 'bm_receptiva',
        descricao: 'BM receptiva aprovada pelo Meta',
        responsavel: 'Rafael',
        observacao: '',
      },
      {
        id: 'h-1779288829176-j9582',
        dataHora: '2026-05-20T14:53:49.176Z',
        tipo: 'facebook',
        descricao: 'Primeiro acesso ao Facebook realizado',
        responsavel: 'Rafael',
        observacao: '',
      },
    ],
    criadoEm: '2026-05-20T14:48:36.850Z',
    atualizadoEm: '2026-05-20T14:54:04.229Z',
  },
]
